project:
  type: website

website:
  title: "Lorenzo Posti's Machine Learning Quarto blog"
  navbar:
    background: light
    foreground: dark
    collapse: true
    right:
      - text: "About this blog"
        file: about_blog.md
      - text: "About me"
        file: about.qmd
      - icon: github
        href: https://github.com/lposti/
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=fDDcGdwAAAAJ&hl=en
      - icon: book-half
        text: " "
        file: lop.qmd

format:
  html:
    theme: lumen
    css: styles.css

execute:
  freeze: auto
